# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wallpaper App UIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wallpaper App UIKit
pod 'Google-Mobile-Ads-SDK'

  target 'Wallpaper App UIKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Wallpaper App UIKitUITests' do
    # Pods for testing
  end

end
