# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

force true

price_tier(0)

submission_information({
    export_compliance_encryption_updated: false,
    export_compliance_uses_encryption: false,
    content_rights_contains_third_party_content: true,
    add_id_info_uses_idfa: true,
    add_id_info_limits_tracking: true
})

app_rating_config_path("./fastlane/metadata/app_store_rating_config.json")

ipa("./fastlane/builds/Wallpaper App UIKit.ipa”)
# 5
submit_for_review(false)
# 6
automatic_release(true)