default_platform(:ios)

platform :ios do
  desc "Checkout branch and merge main"
  lane :update_branches_and_submit do
    checkout_and_merge
    build
    upload
  end

  lane :checkout_and_merge do
    git_switch_branch(branch: "wallpaper/nature”)
    sh(git merge main)
  end

  lane :build do
    enable_automatic_code_signing
    increment_build_number
    gym
  end

  lane :upload do
    deliver
  end
end
