default_platform(:ios)

platform :ios do
  desc "Checkout branch"
  lane :checkout_branch do
    git_switch_branch(branch: "wallpaper/nature”)
  end

  desc "Merge main"
  lane :merge_main_into_branch do
    sh(git merge main)
  end
end
